SELECT
id,
bbl,
power_generation,
city_building,
data_nycha,
rent_stab_1_to_35,
rent_stab_gt_35,
house_of_worship,
hdfc,
mitchell_lama,
prog_j51,
prog_421a,
prog_421a_aff,
prog_202_8,
prog_prac_202,
prog_proj8,
prog_rad
FROM stern.derived_penalty_exception;


SELECT
bbl as "BBL",
nyc_bin as "Building Identification Number (BIN) - 7 digits",
property_name as "Property Name",
"Standalone,Parent,Child",
parent_property_name as "Parent Property Name",
city_building as "City-Owned Building",
address_line_1 as "Address 1 (self-reported)",
postal_code as "Postal Code",
street_number as "Street Number",
street_name as "Street Name",
borough as "Borough",
latitude as "Latitude v2",
longitude as "Longitude v2",
community_board as "Community Board",
council_district as "Council District",
census_tract as "Census Tract",
nta as "Neighborhood Tabulation Areas (NTA)",
qct as "Low-Income Housing Tax Credit Qualified Census Tracts",
generation_date as "LL84 Record Generation Date",
dof_gross_floor_area as "Gross Floor Area (NYC DOF)",
property_use_types as "List of All Property Use Types at Property",
largest_property_use_type as "Largest Property Use Type",
largest_property_use_type_gross_floor_area as "Largest Property Use Type - Gross Floor Area (sqft)",
second_largest_property_use_type as "2nd Largest Property Use Type",
second_largest_property_use_type_gross_floor_area as "2nd Largest Property Use - Gross Floor Area (sqft)",
third_largest_property_use_type as "3rd Largest Property Use Type",
third_largest_property_use_type_gross_floor_area as "3rd Largest Property Use Type - Gross Floor Area (sqft)",
year_built as "Building Construction Year",
number_of_buildings as "Number of Buildings",
occupancy as "Occupancy",
metered_areas as "Metered Areas (Energy)",
energy_star_score as "Energy Star Score",
energy_grade as "Energy Grade",
site_eui as "Site Energy Unit Intensity (EUI) (kBtu/sqft)",
fuel_oil_acr1_use as "Fuel Oil #1 Use (kBtu)",
fuel_oil_acr2_use as "Fuel Oil #2 Use (kBtu)",
fuel_oil_acr4_use as "Fuel Oil #4 Use (kBtu)",
fuel_oil_acr5_acr6_use as "Fuel Oil #5 & 6 Use (kBtu)",
diesel_acr2_use as "Diesel #2 Use (kBtu)",
kerosene_use as "Kerosene Use (kBtu)",
propane_use as "Propane Use (kBtu)",
district_steam_use as "District Steam Use (kBtu)",
naturalgas_use_kbtu as "Natural Gas Use (kBtu)",
naturalgas_use_therms as "Natural Gas Use (therms)",
electricity_use_grid_purchase_kwh as "Electricity Use - Grid Purchase (kWh)",
total_ghg_emissions_metric_ton_co2 as "LL84 Total GHG Emissions (MTCO2e)",
direct_ghg_emissions_metric_ton_co2 as "LL84 Direct GHG Emissions (MTCO2e)",
indirect_ghg_emissions_metric_ton_co2 as "LL84 Indirect GHG Emissions (MTCO2e)",
is_penalty_applicable_in_2024 as "Subject to Compliance Starting in 2024",
exception_type as "Terms of Exception",
exception_name as "Excepted Building Category",
total_carbon_emission_threshold_2024_2029 as "LL97 Total Carbon Emission Threshold 2024_2029",
total_carbon_emission_threshold_2030_2034 as "LL97 Total Carbon Emission Threshold 2030_2034",
total_actual_emission as "LL97 Total Carbon Emissions (MTCO2e)",
emission_excess_2024_2029 as "LL97 Excess Emissions 2024-2029 (MTCO2e)",
emission_excess_2030_2034 as "LL97 Excess Emissions 2030-2034 (MTCO2e)",
emission_penalty_2024_2029 as "LL97 Penalties 2024-2029 (USD)",
emission_penalty_2030_2034 as "LL97 Penalties 2030-2035 (USD)",
owner_name_1 as "Owner-Name 1",
owner_name_2 as "Owner-Name 2",
securitization_type as "Securitization Type",
mail_recipient_name as "Owner-Mail Recipient Name",
mail_careof as "Owner-Portfolio Owner or Agent",
mail_city as "Portfolio owner or Agent mail city",
mail_state as "Portfolio owner or Agent mail state",
usps_address as "Portfolio owner or Agent USPS address",
ownerpluto as "Portfolio owner or Agent USPS address",
"Owner-CorporationNameHDP" as "Owner-Corporation Name HDP",
lien_name as "Lien names"
FROM stern.consolidated_report;
