version: '3'

services:
  postgres:
    image: postgres:12.7
    restart: always
    container_name: stern-local-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./out/postgres_data:/var/lib/postgresql/data
      - ./stern_schema.sql:/docker-entypoint-initdb.d/1schema.sql
