CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

SELECT uuid_generate_v1();

create table CARBON_LIMIT(
ID uuid primary key default uuid_generate_v4(),
OCCUPANCY_GRP VARCHAR(40) not null,
SPACE_USE VARCHAR(40) not null,
CARBON_LIMIT_24_29 decimal(4,2),
CARBON_LIMIT_30_34 decimal(4,2)
);

create table ENERGY_SRC_GHG_COEFF(
ID uuid primary key default uuid_generate_v4(),
ENERGY_SOURCE VARCHAR(40) not null,
GHG_COEFFICIENT decimal(12,12),
GHG_COEFFICIENT_UNIT VARCHAR(40) not null
);

create table PENALTY_VARIABLES(
ID uuid primary key default uuid_generate_v4(),
LARGEST_PROPERTY_USE_TYPE VARCHAR(100),
LARGEST_PROPERTY_USE_TYPE_GROSS_FLOOR_AREA DECIMAL(24,2),
SECOND_LARGEST_PROPERTY_USE_TYPE VARCHAR(100),
SECOND_LARGEST_PROPERTY_USE_TYPE_GROSS_FLOOR_AREA DECIMAL(24,2),
THIRD_LARGEST_PROPERTY_USE_TYPE VARCHAR(100),
THIRD_LARGEST_PROPERTY_USE_TYPE_GROSS_FLOOR_AREA DECIMAL(24,2),
FUEL_OIL_2_USE DECIMAL(24,2),
FUEL_OIL_4_USE DECIMAL(24,2),
NATURALGAS_USE DECIMAL(24,2),
DISTRICT_STEAM_USE DECIMAL(24,2),
ELECTRICITY_USE_GRID_PURCHASE_KWH DECIMAL(24,2)
);

create table PENALTY_EXEMPTION(
ID uuid primary key default uuid_generate_v4(),
BBL BIGINT,
BBL_SELF_REPORTED BIGINT,
PENALTY_EXEMPT_FLAG BOOLEAN
);

create table DOF_LIEN_INFO(
ID uuid primary key default uuid_generate_v4(),
LIEN_NAME VARCHAR(40) not null,
);

create table BBL_LIEN_LINKAGE(
ID uuid primary key default uuid_generate_v4(),
LIEN_NAME VARCHAR(40) not null,
BBL BIGINT,
BBL_SELF_REPORTED BIGINT,
);

create table LL_84(
ID uuid primary key default uuid_generate_v4(),
PROPERTY_ID BIGINT,
PROPERTY_NAME VARCHAR(40),
PARENT_PROPERTY_ID BIGINT,
PARENT_PROPERTY_NAME VARCHAR(40),
CITY_BUILDING VARCHAR(4),
EMAIL VARCHAR(60),
BBL BIGINT,
BBL_SELF_REPORTED BIGINT,
NYC_BIN BIGINT,
ADDRESS_LINE_1 VARCHAR(100),
ADDRESS_LINE_2 VARCHAR(100),
POSTAL_CODE BIGINT,
STREET_NUMBER VARCHAR(100),
STREET_NAME VARCHAR(100),
BOROUGH VARCHAR(50),
DOF_GROSS_FLOOR_AREA DECIMAL(24,2),
SELF_REPORTED_GROSS_FLOOR_AREA DECIMAL(24,2),
PRIMARY_PROPERTY_TYPE VARCHAR(100),
PROPERTY_USE_TYPES VARCHAR(100),
LARGEST_PROPERTY_USE_TYPE VARCHAR(100),
LARGEST_PROPERTY_USE_TYPE_GROSS_FLOOR_AREA DECIMAL(24,2),
SECOND_LARGEST_PROPERTY_USE_TYPE VARCHAR(100),
SECOND_LARGEST_PROPERTY_USE_TYPE_GROSS_FLOOR_AREA DECIMAL(24,2),
THIRD_LARGEST_PROPERTY_USE_TYPE VARCHAR(100),
THIRD_LARGEST_PROPERTY_USE_TYPE_GROSS_FLOOR_AREA DECIMAL(24,2),
YEAR_BUILT INT,
NUMBER_OF_BUILDINGS INT,
OCCUPANCY INT,
METERED_AREAS_ENERGY VARCHAR(40),
METERED_AREAS_WATER VARCHAR(40),
ENERGY_STAR_SCORE INT,
SOURCE_EUI DECIMAL(24,2),
WEATHER_NORMALIZED_SITE_EUI DECIMAL(24,2),
SITE_EUI DECIMAL(24,2),
WEATHER_NORMALIZED_SOURCE_EUI DECIMAL(24,2),
WEATHER_NORMALIZED_SITE_ELECTRICITY_INTENSITY DECIMAL(24,2),
WEATHER_NORMALIZED_SITE_NATURAL_GAS_INTENSITY DECIMAL(24,2),
FUEL_OIL_1_USE DECIMAL(24,2),
FUEL_OIL_2_USE DECIMAL(24,2),
FUEL_OIL_4_USE DECIMAL(24,2),
FUEL_OIL_5_6_USE DECIMAL(24,2),
DISEL_2_USE DECIMAL(24,2),
KEROSENSE_USE DECIMAL(24,2),
PROPANE_USE DECIMAL(24,2),
DISTRICT_STEAM_USE DECIMAL(24,2),
DISTRICT_HOTWATER_USE DECIMAL(24,2),
DISTRICT_CHILLEDWATER_USE DECIMAL(24,2),
NATURALGAS_USE DECIMAL(24,2),
WEATHER_NORMALIZED_SITE_NATURALGAS_USE DECIMAL(24,2),
ELECTRICITY_USE_GRID_PURCHASE_KBTU DECIMAL(24,2),
ELECTRICITY_USE_GRID_PURCHASE_KWH DECIMAL(24,2),
WEATHER_NORMALIZED_SITE_ELECTRICITY_KWH DECIMAL(24,2),
ANNUAL_MAX_DEMAND_KW DECIMAL(24,2),
ANNUAL_MAX_DEMAND_DATE DECIMAL(24,2),
TOTAL_GHG_EMISSIONS_METRIC_TON_CO2 DECIMAL(24,2),
DIRECT_GHG_EMISSIONS_METRIC_TON_CO2 DECIMAL(24,2),
INDIRECT_GHG_EMISSIONS_METRIC_TON_CO2 DECIMAL(24,2),
WATER_USE_ALL_SOURCES_KGAL DECIMAL(24,2),
WATER_USE_INTENSITY_ALL_SOURCES DECIMAL(24,2),
WATER_REQUIRED VARCHAR(4),
GENERATION_DATE TIMESTAMP,
LATITUDE_LONGITUDE_COORDINATES POINT,
COMMUNITY_BOARD DECIMAL(24,2),
COUNCIL_DISTRICT DECIMAL(24,2),
CENSUS_TRACT DECIMAL(24,2),
NTA VARCHAR(100),
CHARS_IN_BIN_COLUMN INT,
NUMBER_OF_TIMES_BIN_REPEATS_IN_TABLE INT,
CHARS_IN_BBL_COLUMN INT,
NUMBER_OF_TIMES_BBL_REPEATS_IN_TABLE INT,
NUMBER_OF_TIMES_PROPERTY_ID_REPEATS_IN_TABLE INT,
STANDALONE_PARENT_CHILD_IND VARCHAR(40)
);