
/* Utility functions */
create extension if not exists "uuid-ossp";

create table FEED_LL84_BBL(
ID SERIAL,
BBL BIGINT not null,
NYC_BIN BIGINT not null,
PROPERTY_ID BIGINT,
PROPERTY_NAME VARCHAR(40),
CITY_BUILDING VARCHAR(4),
EMAIL VARCHAR(60),
ADDRESS_LINE_1 VARCHAR(100),
ADDRESS_LINE_2 VARCHAR(100),
POSTAL_CODE BIGINT,
BOROUGH VARCHAR(50),
DOF_GROSS_FLOOR_AREA DECIMAL(24,2),
SELF_REPORTED_GROSS_FLOOR_AREA DECIMAL(24,2),
PROPERTY_USE_TYPES VARCHAR(100), /*TODO: better data structure*/
LARGEST_PROPERTY_USE_TYPE VARCHAR(100),
LARGEST_PROPERTY_USE_TYPE_GROSS_FLOOR_AREA DECIMAL(24,2),
SECOND_LARGEST_PROPERTY_USE_TYPE VARCHAR(100),
SECOND_LARGEST_PROPERTY_USE_TYPE_GROSS_FLOOR_AREA DECIMAL(24,2),
THIRD_LARGEST_PROPERTY_USE_TYPE VARCHAR(100),
THIRD_LARGEST_PROPERTY_USE_TYPE_GROSS_FLOOR_AREA DECIMAL(24,2),
YEAR_BUILT INT,
NUMBER_OF_BUILDINGS INT,
OCCUPANCY INT,
LATITUDE_LONGITUDE_COORDINATES POINT,
COMMUNITY_BOARD DECIMAL(24,2),
COUNCIL_DISTRICT DECIMAL(24,2),
CENSUS_TRACT DECIMAL(24,2),
NTA VARCHAR(100),
FUEL_OIL_1_USE DECIMAL(24,2),
FUEL_OIL_2_USE DECIMAL(24,2),
FUEL_OIL_4_USE DECIMAL(24,2),
FUEL_OIL_5_6_USE DECIMAL(24,2),
DISEL_2_USE DECIMAL(24,2),
PROPANE_USE DECIMAL(24,2),
DISTRICT_STEAM_USE DECIMAL(24,2),
DISTRICT_CHILLEDWATER_USE DECIMAL(24,2),
NATURALGAS_USE DECIMAL(24,2),
ELECTRICITY_USE_GRID_PURCHASE_KWH DECIMAL(24,2),/**TODO: what if elec is only available in KBTU ? do we convert ? */
TOTAL_GHG_EMISSIONS_METRIC_TON_CO2 DECIMAL(24,2),
ENERGY_STAR_SCORE INT,
SITE_EUI DECIMAL(24,2),/**TODO: check if this datatype can hold possible values */
primary key (BBL, NYC_BIN)
);


/* Lookup tables */
create table LOOKUP_CARBON_LIMIT(
ID SERIAL,
OCCUPANCY_GRP varchar(40) not null,
SPACE_USE VARCHAR(40) not null,
CARBON_LIMIT_2024_2029 decimal(4,2),
CARBON_LIMIT_2030_2034 decimal(4,2)
);

create table LOOKUP_ENERGY_SRC_GHG_COEFF(
ID SERIAL,
ENERGY_SOURCE VARCHAR(40) not null,
GHG_COEFFICIENT decimal(12,12),
GHG_COEFFICIENT_UNIT VARCHAR(40) not null
);

/** Computed values */
create table DERIVED_PENALTY_EXEMPTION(
ID SERIAL,
BBL BIGINT primary key not null, /** TODO: check with Alejandro if penalty exemptions can be tracked at BBL level */
POWER_GENERATION BOOLEAN,
CITY_BUILDING BOOLEAN,
NYCHA BOOLEAN,
RENT_STABLIZED_APTMT BOOLEAN,
HOUSE_OF_WORSHIP BOOLEAN,
HDFC BOOLEAN,
PROJECT_BASED_FED_HOUSING_PROGRAM BOOLEAN,
PENALTY_EXEMPT_FLAG BOOLEAN
);

create table DERIVED_PENALTY_VARIABLES(
ID SERIAL,
BBL BIGINT not null,
NYC_BIN BIGINT not null,
TOTAL_CARBON_EMISSION_THRESHOLD_2024_202 DECIMAL(24,2),
TOTAL_CARBON_EMISSION_THRESHOLD_2030_2034 DECIMAL(24,2),
TOTAL_ACTUAL_EMISSION DECIMAL(24,2),
EMISSION_EXCESS_2024_2029 DECIMAL(24,2),
EMISSION_EXCESS_2030_2034 DECIMAL(24,2),
EMISSION_PENALTY_2024_2029 DECIMAL(24,2),
EMISSION_PENALTY_2030_2034 DECIMAL(24,2),
primary key (BBL, NYC_BIN)
);

create table FEED_SOANA_OWNERSHIP_INFO(
ID SERIAL,
BBL BIGINT primary key not null,
OWNER_1 VARCHAR(100),
OWNER_2 VARCHAR(100),
RECIPIENT_1 VARCHAR(100),
RECIPIENT_2 VARCHAR(100),
MAILING_STREET_1 VARCHAR(300),
MAILING_STREET_2 VARCHAR(300),
MAILING_CITY_1 VARCHAR(40),
MAILING_CITY_2 VARCHAR(40),/**TODO: Check with Alejandro why there is no mailing city 2 in drive doc */
MAILING_STATE_1 VARCHAR(40),
MAILING_STATE_2 VARCHAR(40),/**TODO: Check with Alejandro why there is no mailing state 2 in drive doc */
MAILING_ZIP_1 VARCHAR(40),
MAILING_ZIP_2 VARCHAR(40),/**TODO: Check with Alejandro why there is no mailing zip 2 in drive doc */
MAILING_COUNTRY VARCHAR(40) /** TODO : Check if owner can be living/registered outside US*/
);






