POST http://localhost:9000/penalty
Content-Type: application/json

{
  "largestPropertyUseType":"MultifamilyHousing",
  "secondLargestPropertyUseType":"RetailStore",
  "thirdLargestPropertyUseType":"SocialMeetingHall",
  "largestPropertyUseTypeGrossFloorArea": 7420000,
  "secondLargestPropertyUseTypeGrossFloorArea": 297100,
  "thirdLargestPropertyUseTypeGrossFloorArea": 125490,
  "fuelOil2Use": 32139374,
  "diesel2Use": 2281002,
  "naturalGasUsekBTU": 1310168149
}
