db:
  postgres:
    dao:
      thread:
        pool:
          blocking-queue-size: 4
          executor-name-format: postgres-dao-pool-%d
          size: 4
    hikari:
      maximum-pool-size: 40
      minimum-idle: 10
